<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerImrodxx\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerImrodxx/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerImrodxx.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerImrodxx\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerImrodxx\appProdProjectContainer([
    'container.build_hash' => 'Imrodxx',
    'container.build_id' => 'df3d1ac3',
    'container.build_time' => 1663747392,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerImrodxx');
